<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Andres Emiliano Ramos Gimenez -->
<!DOCTYPE oferta [
    <!ELEMENT oferta (vehiculo+)>
    <!ELEMENT vehiculo (marca, modelo, motor, matricula, kilometros, precio_inicial, precio_oferta, extra*, foto*)>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT motor (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT kilometros (#PCDATA)>
    <!ELEMENT precio_inicial (#PCDATA)>
    <!ELEMENT precio_oferta (#PCDATA)>
    <!ELEMENT extra (#PCDATA)>
    <!ELEMENT foto (#PCDATA)>
    <!ATTLIST foto imagen CDATA #IMPLIED>
    <!ATTLIST extra valor CDATA "0">
    <!ATTLIST motor combustible (diesel|gasolina) #REQUIRED>
    <!ATTLIST modelo color (null|gris|blanco|champagne) #IMPLIED>
]>
<oferta>
    <vehiculo>
        <marca></marca>
        <modelo color="null"></modelo>
        <motor combustible="diesel"></motor>
        <matricula></matricula>
        <kilometros></kilometros>
        <precio_inicial></precio_inicial>
        <precio_oferta></precio_oferta>
        <extra valor=""></extra>
        <extra valor=""></extra>
        <extra valor=""></extra>
        <foto imagen="" />
        <foto imagen="" />
    </vehiculo>

    <vehiculo>
        <marca></marca>
        <modelo color="champagne"></modelo>
        <motor combustible="diesel"></motor>
        <matricula></matricula>
        <kilometros></kilometros>
        <precio_inicial></precio_inicial>
        <precio_oferta></precio_oferta>
        <extra valor=""></extra>
        <extra valor=""></extra>
        <extra valor=""></extra>
        <foto imagen="" />
        <foto imagen="" />
    </vehiculo>

    <vehiculo>
        <marca></marca>
        <modelo color="gris"></modelo>
        <motor combustible="diesel"></motor>
        <matricula></matricula>
        <kilometros></kilometros>
        <precio_inicial></precio_inicial>
        <precio_oferta></precio_oferta>
        <extra valor=""></extra>
        <extra valor=""></extra>
        <extra valor=""></extra>
        <foto imagen="" />
        <foto imagen="" />
    </vehiculo>
</oferta>